export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PROTOCOL: 'PROTOCOL',
  SECURITY: 'SECURITY',
  DELEGATE: 'DELEGATE',
  GUEST: 'GUEST'
};

export const PERMISSIONS = {
  users: [ROLES.SUPER_ADMIN],
  stakeholders: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL],
  csr_ledger: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL], // Access control for CSR & Delegate Registration
  rsvp: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL, ROLES.SECURITY, ROLES.DELEGATE, ROLES.GUEST],
  analytics: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  oversight: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  engagement: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL],
  tasks: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL, ROLES.SECURITY],
  agenda: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL, ROLES.SECURITY, ROLES.DELEGATE, ROLES.GUEST],
  protocol: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL],
  seating: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PROTOCOL],
  security: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SECURITY]
};